<?php
/**
 * The template for displaying all pages
 * This is the template that displays all pages by default
 *
 * @package Westpace_Material
 * @version 3.0.0
 */

get_header();
?>

<main id="primary" class="site-main">
    <div class="container">
        <div class="content-layout <?php echo westpace_has_sidebar() ? 'has-sidebar' : 'full-width'; ?>">
            
            <div class="main-content">
                <?php while (have_posts()) : the_post(); ?>
                    
                    <article id="page-<?php the_ID(); ?>" <?php post_class('page-article'); ?>>
                        
                        <?php if (has_post_thumbnail() && !is_front_page()) : ?>
                            <div class="page-featured-image">
                                <?php the_post_thumbnail('hero-banner', array('loading' => 'eager')); ?>
                            </div>
                        <?php endif; ?>
                        
                        <div class="page-content-wrapper">
                            
                            <header class="page-header">
                                <?php if (!is_front_page()) : ?>
                                    <h1 class="page-title"><?php the_title(); ?></h1>
                                    
                                    <?php 
                                    // Page meta information
                                    $show_meta = get_post_meta(get_the_ID(), '_westpace_show_page_meta', true);
                                    if ($show_meta !== 'no') :
                                    ?>
                                        <div class="page-meta">
                                            <div class="page-meta-item">
                                                <span class="material-icons-round">schedule</span>
                                                <span><?php esc_html_e('Last updated:', 'westpace-material'); ?> <?php echo get_the_modified_date(); ?></span>
                                            </div>
                                            
                                            <?php if (comments_open() || get_comments_number()) : ?>
                                                <div class="page-meta-item">
                                                    <span class="material-icons-round">comment</span>
                                                    <?php
                                                    comments_popup_link(
                                                        esc_html__('Leave a comment', 'westpace-material'),
                                                        esc_html__('1 Comment', 'westpace-material'),
                                                        esc_html__('% Comments', 'westpace-material')
                                                    );
                                                    ?>
                                                </div>
                                            <?php endif; ?>
                                            
                                            <?php
                                            // Reading time for longer pages
                                            $reading_time = westpace_get_reading_time();
                                            if ($reading_time) :
                                            ?>
                                                <div class="page-meta-item">
                                                    <span class="material-icons-round">schedule</span>
                                                    <span><?php echo $reading_time; ?></span>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </header>

                            <!-- Table of Contents for long pages -->
                            <?php 
                            $show_toc = get_post_meta(get_the_ID(), '_westpace_show_toc', true);
                            if ($show_toc === 'yes') :
                            ?>
                                <div class="table-of-contents-wrapper">
                                    <div class="toc-card material-card elevation-1">
                                        <h3 class="toc-title">
                                            <span class="material-icons-round">list</span>
                                            <?php esc_html_e('Table of Contents', 'westpace-material'); ?>
                                        </h3>
                                        <div id="table-of-contents">
                                            <!-- Generated by JavaScript -->
                                        </div>
                                    </div>
                                </div>
                            <?php endif; ?>

                            <!-- Page Content -->
                            <div class="page-content entry-content">
                                <?php
                                the_content();
                                
                                wp_link_pages(array(
                                    'before'      => '<div class="page-links"><span class="page-links-title">' . __('Pages:', 'westpace-material') . '</span>',
                                    'after'       => '</div>',
                                    'link_before' => '<span class="page-link">',
                                    'link_after'  => '</span>',
                                ));
                                ?>
                            </div>

                            <!-- Child Pages Section -->
                            <?php
                            $child_pages = get_children(array(
                                'post_parent' => get_the_ID(),
                                'post_type'   => 'page',
                                'post_status' => 'publish',
                                'orderby'     => 'menu_order',
                                'order'       => 'ASC',
                            ));

                            if (!empty($child_pages)) :
                            ?>
                                <div class="child-pages-section">
                                    <h3 class="child-pages-title">
                                        <span class="material-icons-round">folder</span>
                                        <?php esc_html_e('In this section:', 'westpace-material'); ?>
                                    </h3>
                                    <div class="child-pages-grid">
                                        <?php foreach ($child_pages as $child_page) : ?>
                                            <div class="child-page-card material-card elevation-1">
                                                <?php if (has_post_thumbnail($child_page->ID)) : ?>
                                                    <div class="child-page-thumbnail">
                                                        <a href="<?php echo esc_url(get_permalink($child_page->ID)); ?>">
                                                            <?php echo get_the_post_thumbnail($child_page->ID, 'blog-featured'); ?>
                                                        </a>
                                                    </div>
                                                <?php endif; ?>
                                                
                                                <div class="child-page-content">
                                                    <h4 class="child-page-title">
                                                        <a href="<?php echo esc_url(get_permalink($child_page->ID)); ?>">
                                                            <?php echo esc_html($child_page->post_title); ?>
                                                        </a>
                                                    </h4>
                                                    
                                                    <?php if (!empty($child_page->post_excerpt)) : ?>
                                                        <p class="child-page-excerpt">
                                                            <?php echo esc_html($child_page->post_excerpt); ?>
                                                        </p>
                                                    <?php else : ?>
                                                        <p class="child-page-excerpt">
                                                            <?php echo esc_html(wp_trim_words($child_page->post_content, 20)); ?>
                                                        </p>
                                                    <?php endif; ?>
                                                    
                                                    <a href="<?php echo esc_url(get_permalink($child_page->ID)); ?>" class="child-page-link">
                                                        <?php esc_html_e('Learn More', 'westpace-material'); ?>
                                                        <span class="material-icons-round">arrow_forward</span>
                                                    </a>
                                                </div>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            <?php endif; ?>

                        </div>

                        <!-- Page Footer -->
                        <footer class="page-footer">
                            <?php
                            // Edit link for logged-in users
                            edit_post_link(
                                sprintf(
                                    wp_kses(
                                        __('Edit <span class="screen-reader-text">"%s"</span>', 'westpace-material'),
                                        array(
                                            'span' => array(
                                                'class' => array(),
                                            ),
                                        )
                                    ),
                                    wp_kses_post(get_the_title())
                                ),
                                '<span class="edit-link">',
                                '</span>'
                            );
                            ?>
                        </footer>

                    </article>

                    <?php
                    // If comments are open or we have at least one comment, load up the comment template.
                    if (comments_open() || get_comments_number()) :
                        comments_template();
                    endif;
                    ?>

                <?php endwhile; ?>
            </div>

            <?php if (westpace_has_sidebar()) : ?>
                <aside id="secondary" class="widget-area sidebar">
                    <?php dynamic_sidebar(westpace_get_sidebar()); ?>
                </aside>
            <?php endif; ?>

        </div>
    </div>
</main>

<style>
/* Page Template Styles */
.page-article {
    background: white;
    border-radius: var(--radius-xl);
    overflow: hidden;
    box-shadow: var(--shadow-md);
    margin-bottom: var(--space-8);
}

.page-featured-image {
    position: relative;
    height: 400px;
    overflow: hidden;
}

.page-featured-image img {
    width: 100%;
    height: 100%;
    object-fit: cover;
}

.page-content-wrapper {
    padding: var(--space-8);
}

.page-header {
    margin-bottom: var(--space-8);
    text-align: center;
    border-bottom: 1px solid var(--gray-200);
    padding-bottom: var(--space-6);
}

.page-title {
    font-size: var(--text-4xl);
    font-weight: var(--font-weight-bold);
    color: var(--gray-900);
    margin-bottom: var(--space-4);
    line-height: 1.2;
}

.page-meta {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
    gap: var(--space-6);
    color: var(--gray-600);
    font-size: var(--text-sm);
}

.page-meta-item {
    display: flex;
    align-items: center;
    gap: var(--space-2);
}

.page-meta-item .material-icons-round {
    font-size: 1rem;
}

.table-of-contents-wrapper {
    margin: var(--space-8) 0;
    max-width: 300px;
    float: right;
    margin-left: var(--space-6);
}

.toc-card {
    padding: var(--space-6);
    border-radius: var(--radius-lg);
    background: var(--gray-50);
    border: 1px solid var(--gray-200);
    position: sticky;
    top: 100px;
}

.toc-title {
    display: flex;
    align-items: center;
    gap: var(--space-2);
    font-size: var(--text-lg);
    font-weight: var(--font-weight-semibold);
    color: var(--gray-900);
    margin-bottom: var(--space-4);
}

#table-of-contents {
    font-size: var(--text-sm);
}

#table-of-contents ul {
    list-style: none;
    padding-left: 0;
    margin: 0;
}

#table-of-contents li {
    margin-bottom: var(--space-2);
}

#table-of-contents a {
    color: var(--gray-600);
    text-decoration: none;
    display: block;
    padding: var(--space-1) 0;
    transition: color var(--transition-fast);
    border-radius: var(--radius-md);
}

#table-of-contents a:hover,
#table-of-contents a.active {
    color: var(--primary-600);
    background: var(--primary-50);
    padding-left: var(--space-2);
}

.page-content {
    font-size: var(--text-lg);
    line-height: 1.8;
    color: var(--gray-700);
}

.page-content h2,
.page-content h3,
.page-content h4,
.page-content h5,
.page-content h6 {
    margin: var(--space-8) 0 var(--space-4);
    color: var(--gray-900);
    font-weight: var(--font-weight-semibold);
    line-height: 1.3;
    scroll-margin-top: 100px;
}

.page-content h2 {
    font-size: var(--text-2xl);
    border-bottom: 2px solid var(--gray-200);
    padding-bottom: var(--space-2);
}

.page-content h3 {
    font-size: var(--text-xl);
}

.page-content h4 {
    font-size: var(--text-lg);
}

.page-content p {
    margin-bottom: var(--space-6);
}

.page-content ul,
.page-content ol {
    margin-bottom: var(--space-6);
    padding-left: var(--space-6);
}

.page-content li {
    margin-bottom: var(--space-2);
}

.page-content blockquote {
    border-left: 4px solid var(--primary-500);
    background: var(--primary-50);
    padding: var(--space-6);
    margin: var(--space-8) 0;
    border-radius: 0 var(--radius-lg) var(--radius-lg) 0;
    font-style: italic;
    font-size: var(--text-lg);
}

.page-content img {
    border-radius: var(--radius-lg);
    box-shadow: var(--shadow-md);
    max-width: 100%;
    height: auto;
}

.page-links {
    margin: var(--space-8) 0;
    text-align: center;
}

.page-links-title {
    font-weight: var(--font-weight-semibold);
    margin-right: var(--space-4);
}

.page-link {
    display: inline-block;
    padding: var(--space-2) var(--space-4);
    margin: 0 var(--space-1);
    background: var(--gray-100);
    border-radius: var(--radius-md);
    text-decoration: none;
    color: var(--gray-700);
    transition: all var(--transition-fast);
}

.page-link:hover {
    background: var(--primary-600);
    color: white;
    text-decoration: none;
}

.child-pages-section {
    margin: var(--space-12) 0;
    padding: var(--space-8);
    background: var(--gray-50);
    border-radius: var(--radius-xl);
}

.child-pages-title {
    display: flex;
    align-items: center;
    gap: var(--space-2);
    font-size: var(--text-2xl);
    font-weight: var(--font-weight-semibold);
    color: var(--gray-900);
    margin-bottom: var(--space-6);
}

.child-pages-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: var(--space-6);
}

.child-page-card {
    background: white;
    border-radius: var(--radius-lg);
    overflow: hidden;
    transition: all var(--transition-normal);
    border: 1px solid var(--gray-200);
}

.child-page-card:hover {
    transform: translateY(-4px);
    box-shadow: var(--shadow-lg);
}

.child-page-thumbnail {
    aspect-ratio: 16/9;
    overflow: hidden;
}

.child-page-thumbnail img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    transition: transform var(--transition-normal);
}

.child-page-card:hover .child-page-thumbnail img {
    transform: scale(1.05);
}

.child-page-content {
    padding: var(--space-6);
}

.child-page-title {
    font-size: var(--text-lg);
    font-weight: var(--font-weight-semibold);
    margin-bottom: var(--space-3);
}

.child-page-title a {
    color: var(--gray-900);
    text-decoration: none;
}

.child-page-title a:hover {
    color: var(--primary-600);
}

.child-page-excerpt {
    color: var(--gray-600);
    line-height: 1.6;
    margin-bottom: var(--space-4);
}

.child-page-link {
    display: inline-flex;
    align-items: center;
    gap: var(--space-2);
    color: var(--primary-600);
    text-decoration: none;
    font-weight: var(--font-weight-medium);
    transition: all var(--transition-fast);
}

.child-page-link:hover {
    color: var(--primary-700);
    text-decoration: none;
}

.page-footer {
    padding: var(--space-6) var(--space-8) var(--space-8);
    border-top: 1px solid var(--gray-200);
    text-align: center;
}

.edit-link a {
    display: inline-flex;
    align-items: center;
    gap: var(--space-2);
    padding: var(--space-2) var(--space-4);
    background: var(--gray-100);
    color: var(--gray-700);
    text-decoration: none;
    border-radius: var(--radius-md);
    font-size: var(--text-sm);
    transition: all var(--transition-fast);
}

.edit-link a:hover {
    background: var(--primary-600);
    color: white;
    text-decoration: none;
}

/* Responsive Design */
@media (max-width: 1024px) {
    .table-of-contents-wrapper {
        float: none;
        max-width: 100%;
        margin: var(--space-6) 0;
    }
    
    .toc-card {
        position: static;
    }
}

@media (max-width: 768px) {
    .page-content-wrapper {
        padding: var(--space-6);
    }
    
    .page-title {
        font-size: var(--text-2xl);
    }
    
    .page-meta {
        flex-direction: column;
        gap: var(--space-2);
    }
    
    .child-pages-grid {
        grid-template-columns: 1fr;
    }
    
    .page-featured-image {
        height: 250px;
    }
}
</style>

<script>
// Generate Table of Contents
document.addEventListener('DOMContentLoaded', function() {
    const tocContainer = document.getElementById('table-of-contents');
    if (tocContainer) {
        const headings = document.querySelectorAll('.page-content h2, .page-content h3, .page-content h4');
        
        if (headings.length > 0) {
            const tocList = document.createElement('ul');
            
            headings.forEach(function(heading, index) {
                // Add ID to heading if it doesn't have one
                if (!heading.id) {
                    heading.id = 'heading-' + index;
                }
                
                const listItem = document.createElement('li');
                const link = document.createElement('a');
                
                link.href = '#' + heading.id;
                link.textContent = heading.textContent;
                link.style.paddingLeft = (heading.tagName === 'H3' ? '1rem' : heading.tagName === 'H4' ? '2rem' : '0');
                
                listItem.appendChild(link);
                tocList.appendChild(listItem);
            });
            
            tocContainer.appendChild(tocList);
            
            // Add smooth scrolling and active state
            const tocLinks = tocContainer.querySelectorAll('a');
            tocLinks.forEach(function(link) {
                link.addEventListener('click', function(e) {
                    e.preventDefault();
                    const targetId = this.getAttribute('href').substring(1);
                    const targetElement = document.getElementById(targetId);
                    
                    if (targetElement) {
                        targetElement.scrollIntoView({
                            behavior: 'smooth',
                            block: 'start'
                        });
                        
                        // Update active state
                        tocLinks.forEach(l => l.classList.remove('active'));
                        this.classList.add('active');
                    }
                });
            });
        } else {
            // Hide TOC if no headings found
            const tocWrapper = document.querySelector('.table-of-contents-wrapper');
            if (tocWrapper) {
                tocWrapper.style.display = 'none';
            }
        }
    }
});
</script>

<?php
get_footer();
?>